export const propertyData = [
  {
    id: 1,
    imageSrc: "/svg/property1.svg",
    title: "Skyper Pool Apartment",
    location: "4330 Bell Shoals Rd",
    price: "280,000",
    bath: "4",
    bed: "2",
    sqr: "450",
    propertyTypes: ["FOR SALE"],
  },
  {
    id: 2,
    imageSrc: "/svg/property3.svg",
    title: "North Dillard Street",
    location: "1020 Bloomingdale Ave",
    price: "280",
    bath: "4",
    bed: "2",
    sqr: "250",
    month: "month",
    propertyTypes: ["FOR RENT", "FEATURE"],
  },
  {
    id: 3,
    imageSrc: "/svg/property2.svg",
    title: "Eaton Garth Penthouse",
    location: "7722 18th Ave, Brooklyn",
    price: "180,000",
    bath: "4",
    bed: "2",
    sqr: "450",
    propertyTypes: ["FOR SALE", "FEATURE"],
  },
];
